import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Address.module.css'
import BottomNavbar from '../components/BottomNavbar'

export default function Address() {
  return (
    <div className={styles.basecontainer}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>

          <div className={styles.appBarContainer}>
            <Image src="/leftarrow.png" width="24px" height="24px" layout="fixed" />
            <div className={styles.appBarTextContainer}>

              <div className={styles.appBarText}>
                Perbarui Alamat
              </div>
            </div>
          </div>
          <div className={styles.separator}></div>

          <div className={styles.inputContainer}>
            <input className={styles.textInput} type="text" placeholder="Jawa" />
            <input className={styles.textInput} type="text" placeholder="Kabupaten / Kota" />
            <input className={styles.textInput} type="text" placeholder="Kecamatan" />
            <input className={styles.textInput} type="text" placeholder="Kelurahan" />
            <input className={styles.textInput} type="text" placeholder="Kode Pos" />
            <input className={styles.textInput} type="text" placeholder="Detail Lainnya (Contoh RT/RW, Blok)" />
          </div>
        </main>

        <footer className={styles.footer}>
          <BottomNavbar />
        </footer>
      </div>
    </div>
  )
}
