import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import BottomNavbar from '../components/BottomNavbar'

export default function Home() {
  return (
    <div className={styles.basecontainer}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.headingBackground}>
        </div>
        <main className={styles.main}>

          <div className={styles.heading}>

            <div className={styles.userInfoContainer}>
              <Image src="/welcome.png" width="64px" height="64px" />
              <div className={styles.userInfo}>
                <div className={styles.userInfoText}>
                  <div className={styles.userInfoTextWelcome}>
                    Selamat datang,
                  </div>
                  <div className={styles.userInfoTextName}>
                    Fulan bin Fulan
                  </div>
                </div>
                <div className={styles.donationBasket}>
                  <Image src="/donationbasket.png" width="48px" height="48px" />
                </div>
              </div>

            </div>

            <div className={styles.donationSummaryContainer}>
              <div className={styles.donationSummaryAmount}>
                Rp 250.000
              </div>
              <div className={styles.donationSummaryMessage}>
                <div className={styles.donationSummaryIcon}>
                  <Image src="/staricon.png" width="20px" height="20px" layout="fixed" />
                </div>
                <div className={styles.donationSummaryText}>
                  Telah antum bagikan kepada saudara-saudara kita yang membutuhkan
                </div>
              </div>
            </div>

            <div className={styles.programLPContainer}>
              <div className={styles.programLPItem}>
                <div className={styles.programLPItemIcon}>
                  <Image src="/infaq.png" width="32px" height="32px" layout="fixed" />
                </div>
                <div className={styles.programLPItemText}>
                  Infaq & Donasi
                </div>
              </div>
              <div className={styles.programLPSeparator}>
              </div>
              <div className={styles.programLPItem}>
                <div className={styles.programLPItemIcon}>
                  <Image src="/interestrate.png" width="32px" height="32px" layout="fixed" />
                </div>
                <div className={styles.programLPItemText}>
                  Dana Ribawi
                </div>
              </div>
            </div>



          </div>
          <div className={styles.titleContainer}>
            <div className={styles.titleText}>
              Program Keluarga
            </div>
            <div className={styles.titleButton}>
              Lihat Semua
            </div>
          </div>


          <div className={styles.carouselContainer}>
            <div className={styles.carouselItem}>
              <div className={styles.carouselItemBackground}>
                <Image src="/carousel1.png" width="156px" height="208px" />
              </div>
              <div className={styles.carouselItemContainer}>
                <div className={styles.carouselItemTextContainer}>
                  <div className={styles.carouselItemText}>
                    Kebutuhan Dapur untuk Mak Painem
                  </div>
                  <div className={styles.carouselItemLocation}>
                    <div className={styles.carouselItemLocationIcon}>
                      <Image src="/mappinicon.png" width="12px" height="12px" />
                    </div>
                    <div className={styles.carouselItemLocationText}>
                      Lumajang, Jawa Timur
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.carouselItem}>
              <div className={styles.carouselItemBackground}>
                <Image src="/carousel2.png" width="156px" height="208px" />
              </div>
              <div className={styles.carouselItemContainer}>
                <div className={styles.carouselItemTextContainer}>
                  <div className={styles.carouselItemText}>
                    Bantu Raya Kembali Berlari Di Lorong
                  </div>
                  <div className={styles.carouselItemLocation}>
                    <div className={styles.carouselItemLocationIcon}>
                      <Image src="/mappinicon.png" width="12px" height="12px" />
                    </div>
                    <div className={styles.carouselItemLocationText}>
                      Bandung, Jawa Barat
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.carouselItem}>
              <div className={styles.carouselItemBackground}>
                <Image src="/carousel3.png" width="156px" height="208px" />
              </div>
              <div className={styles.carouselItemContainer}>
                <div className={styles.carouselItemTextContainer}>
                  <div className={styles.carouselItemText}>
                    Zat Kapur Sudah Lama Larut Dalam
                  </div>
                  <div className={styles.carouselItemLocation}>
                    <div className={styles.carouselItemLocationIcon}>
                      <Image src="/mappinicon.png" width="12px" height="12px" />
                    </div>
                    <div className={styles.carouselItemLocationText}>
                      Nusa Pelida, Bali Timur
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>


          <div className={styles.titleContainer}>
            <div className={styles.titleText}>
              Program Donasi
            </div>
            <div className={styles.titleButton}>
              Lihat Semua
            </div>
          </div>

          <div className={styles.filterContainer}>
            <div className={styles.filterItem}>
              <div className={styles.filterItemIcon}>
                <Image src="/all.png" width="20px" height="20px" />
              </div>
              <div className={styles.filterItemText}>
                Semua
              </div>
            </div>
            <div className={styles.filterItem}>
              <div className={styles.filterItemIcon}>
                <Image src="/national.png" width="20px" height="20px" />
              </div>
              <div className={styles.filterItemText}>
                Nasional
              </div>
            </div>
            <div className={styles.filterItem}>
              <div className={styles.filterItemIcon}>
                <Image src="/world.png" width="20px" height="20px" />
              </div>
              <div className={styles.filterItemText}>
                Internasional
              </div>
            </div>
          </div>

          <div className={styles.donationProgramContainer}>
            <div className={styles.donationProgramItem}>

              <Image src="/water.png" width="64px" height="64px" layout="fixed" />
              <div className={styles.donationProgramItemTextContainer}>
                <div className={styles.donationProgramItemText}>
                  Alirkan Sumber Kehidupan untuk Saudara Kita
                </div>
                <div className={styles.donationProgramItemLocation}>
                  <div className={styles.donationProgramItemLocationIcon}>
                    <Image src="/mappinicongray.png" width="12px" height="12px" />
                  </div>
                  <div className={styles.donationProgramItemLocationText}>
                    Lumajang, Jawa Timur
                  </div>
                </div>
              </div>


            </div>
            <div className={styles.donationProgramItem}>

              <Image src="/volcano.png" width="64px" height="64px" layout="fixed" />
              <div className={styles.donationProgramItemTextContainer}>
                <div className={styles.donationProgramItemText}>
                  #Siaga Bencana - Solidaritas untuk Korban Bencana Alam
                </div>
                <div className={styles.donationProgramItemLocation}>
                  <div className={styles.donationProgramItemLocationIcon}>
                    <Image src="/mappinicongray.png" width="12px" height="12px" />
                  </div>
                  <div className={styles.donationProgramItemLocationText}>
                    Lumajang, Jawa Timur
                  </div>
                </div>
              </div>


            </div>
            <div className={styles.donationProgramItem}>

              <Image src="/earthquake.png" width="64px" height="64px" layout="fixed" />
              <div className={styles.donationProgramItemTextContainer}>
                <div className={styles.donationProgramItemText}>
                  #Siaga Bencana - Solidaritas untuk Korban Gempa NTT
                </div>
                <div className={styles.donationProgramItemLocation}>
                  <div className={styles.donationProgramItemLocationIcon}>
                    <Image src="/mappinicongray.png" width="12px" height="12px" />
                  </div>
                  <div className={styles.donationProgramItemLocationText}>
                    Lumajang, Jawa Timur
                  </div>
                </div>
              </div>
            </div>
          </div>

        </main>

        <footer className={styles.footer}>
          <BottomNavbar />
        </footer>
      </div>
    </div>
  )
}
