import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Invoice.module.css'
import BottomNavbar from '../components/BottomNavbar'
import { useState } from 'react'

export default function Invoice() {

  const [isExpand, toggleExpand] = useState(false)

  return (
    <div className={styles.basecontainer}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.appBarContainer}>
          <div className={styles.appBarImageContainer}>
            <Image src="/leftarrow.png" width="24px" height="24px" layout="fixed" />
            <Image src="/brandlogo.png" width="86px" height="40px" layout="fixed" />
            <Image src="/rightaction.png" width="40px" height="47px" layout="fixed" />
          </div>
          <div className={styles.separator}></div>
        </div>
        <main className={styles.main}>



          <div className={styles.targetImage}>
            <Image src="/boilinglarge.png" width="327px" height="245px" layout="fixed" />
          </div>

          <div className={styles.targetInfoTextContainer}>
            <div className={styles.targetInfoText}>
              Senyawa Kapur Sudah Larut di Dalam Darah
            </div>
            <div className={styles.targetInfoSpecification}>
              Tagihan Listrik 450 KWH
            </div>
            <div className={styles.targetInfoLocation}>
              <div className={styles.targetInfoLocationIcon}>
                <Image src="/mappinicongray.png" width="12px" height="12px" />
              </div>
              <div className={styles.targetInfoLocationText}>
                Payakumbuh, Sumatera Barat
              </div>
              <div className={styles.separatorDot}></div>
              <div className={styles.targetInfoCategory}>
                Program Berbagi
              </div>

            </div>

          </div>
          <div className={styles.separator}></div>
          <div className={styles.donationBillContainer}>
            <div className={styles.donationBillText}>
              Total Donasi
            </div>
            <div className={styles.donationBillNominal}>
              Rp 100.000
            </div>
          </div>

          <div className={styles.transactionInfoContainer}>
            <div className={styles.transactionInfoImage}>
              <Image src="/code.png" width="100px" height="100px" layout="fixed" />
            </div>
            <div className={styles.transactionInfoTextContainer}>
              <div className={styles.transactionInfoDate}>
                <div className={styles.transactionInfoDateItem}>
                  <div className={styles.transactionInfoTextTitle}>
                    Transaksi
                  </div>
                  <div className={styles.transactionInfoTextContent}>
                    31 Des, 2021
                  </div>
                </div>
                <div className={styles.transactionInfoDateItem}>
                  <div className={styles.transactionInfoTextTitle}>
                    Referensi
                  </div>
                  <div className={styles.transactionInfoTextContent}>
                    #3121AB
                  </div>
                </div>
              </div>
              <div className={styles.transactionInfoStatus}>
                <div className={styles.transactionInfoTextTitle}>
                  Status
                </div>
                <div className={styles.transactionInfoTextStatus}>
                  Selesai
                </div>
              </div>
            </div>
          </div>
          <div className={styles.separator}></div>
          <div className={styles.descriptionContainer}>
            <div className={styles.descriptionTitle}>
              Laporan Donasi
            </div>
            <div className={isExpand ? styles.descriptionTextExpanded : styles.descriptionText}>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et in augue praesent tempus tristique morbi vitae in. Cras ligula consequat, sed risus facilisis. Sodales egestas dolor, vel integer sed arcu. Felis dui arcu id faucibus. Nisl mauris etiam tincidunt mattis in nam facilisi integer. Bibendum bibendum pharetra at varius egestas. Tristique sed tellus laoreet at ut tortor suscipit pellentesque quis. Amet iaculis gravida purus sit pulvinar. Iaculis fames eu, at nibh arcu.
            </div>
            <a className={isExpand ? styles.descriptionTextToggleHidden : styles.descriptionTextToggle} onClick={() => toggleExpand(true)}>
              Baca Lebih Lanjut
            </a>
          </div>

          <div className={styles.conditionCarouselContainer}>
            <div className={styles.conditionCarouselTitle}>
              Sebelum
            </div>
            <div className={styles.conditionCarouselItemContainer}>
              <div className={styles.conditionCarouselItem}>
                <div className={styles.conditionCarouselItemBackground}>
                  <Image src="/boiling.png" width="80px" height="80px" layout="fixed" />
                </div>
              </div>
              <div className={styles.conditionCarouselItem}>
                <div className={styles.conditionCarouselItemBackground}>
                  <Image src="/kitchen.png" width="80px" height="80px" layout="fixed" />
                </div>
              </div>
              <div className={styles.conditionCarouselItem}>
                <div className={styles.conditionCarouselItemBackground}>
                  <Image src="/bicycle.png" width="80px" height="80px" layout="fixed" />
                </div>
              </div>
              <div className={styles.conditionCarouselItem}>
                <div className={styles.conditionCarouselItemBackground}>
                  <Image src="/window.png" width="80px" height="80px" layout="fixed" />
                </div>
              </div>

            </div>
          </div>

          <div className={styles.conditionCarouselContainer}>
            <div className={styles.conditionCarouselTitle}>
              Sesudah
            </div>
            <div className={styles.conditionCarouselItemContainer}>
              <div className={styles.conditionCarouselItem}>
                <div className={styles.conditionCarouselItemBackground}>
                  <Image src="/brand.png" width="80px" height="80px" layout="fixed" />
                </div>
              </div>
              <div className={styles.conditionCarouselItem}>
                <div className={styles.conditionCarouselItemBackground}>
                  <Image src="/island.png" width="80px" height="80px" layout="fixed" />
                </div>
              </div>
              <div className={styles.conditionCarouselItem}>
                <div className={styles.conditionCarouselItemBackground}>
                  <Image src="/laptop.png" width="80px" height="80px" layout="fixed" />
                </div>
              </div>
            </div>
          </div>
        </main>

        <footer className={styles.footer}>
          <BottomNavbar />
        </footer>
      </div >
    </div >
  )
}
