import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Transaction.module.css'
import BottomNavbar from '../components/BottomNavbar'

export default function Transaction() {
  return (
    <div className={styles.basecontainer}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.appBarContainer}>
          <div className={styles.appBarImageContainer}>
            <Image src="/leftarrow.png" width="24px" height="24px" layout="fixed" />
            <Image src="/brandlogo.png" width="86px" height="40px" layout="fixed" />
            <Image src="/rightaction.png" width="40px" height="47px" layout="fixed" />
          </div>
          <div className={styles.separator}></div>
        </div>
        <main className={styles.main}>

          <div className={styles.tabContainer}>
            <div className={`${styles.tabItem} ${styles.tabItemSelected}`}>
              <div className={styles.tabItemText}>
                Diproses
              </div>
            </div>
            <div className={styles.tabItem}>
              <div className={styles.tabItemText}>
                Selesai
              </div>
            </div>
            <div className={styles.tabItem}>
              <div className={styles.tabItemText}>
                Dibatalkan
              </div>
            </div>
          </div>


          <div className={styles.transactionContainer}>
            <div className={styles.transactionItem}>

              <Image src="/boiling.png" width="48px" height="48px" layout="fixed" />
              <div className={styles.transactionItemTextContainer}>
                <div className={styles.transactionItemText}>
                  Invoice : 3121AB
                </div>
                <div className={styles.transactionItemDate}>

                  <div className={styles.transactionItemDateText}>
                    31 Des 2021 <div className={styles.separatorDot}></div> 3 Donasi
                  </div>


                </div>

              </div>
              <div className={styles.transactionItemNominal}>
                Rp 138.546
              </div>

            </div>
            <div className={styles.transactionItem}>

              <Image src="/shoes.png" width="48px" height="48px" layout="fixed" />
              <div className={styles.transactionItemTextContainer}>
                <div className={styles.transactionItemText}>
                  Invoice : 0122BC
                </div>
                <div className={styles.transactionItemDate}>

                  <div className={styles.transactionItemDateText}>
                    01 Jan 2022 <div className={styles.separatorDot}></div> 1 Donasi
                  </div>
                </div>


              </div>
              <div className={styles.transactionItemNominal}>
                Rp 50.000
              </div>

            </div>
          </div>

        </main>

        <footer className={styles.footer}>
          <BottomNavbar />
        </footer>
      </div>
    </div>
  )
}
