import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Transaction.module.css'
import BottomNavbar from '../components/BottomNavbar'

export default function Transaction() {
  return (
    <div className={styles.basecontainer}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.appBarContainer}>
          <div className={styles.appBarImageContainer}>
            <Image src="/leftarrow.png" width="24px" height="24px" layout="fixed" />
            <Image src="/brandlogo.png" width="86px" height="40px" layout="fixed" />
            <Image src="/rightaction.png" width="40px" height="47px" layout="fixed" />
          </div>
          <div className={styles.separator}></div>
        </div>
        <main className={styles.main}>

          <div className={styles.tabContainer}>
            <div className={styles.tabItem}>
              <div className={styles.tabItemText}>
                Diproses
              </div>
            </div>
            <div className={`${styles.tabItem} ${styles.tabItemSelected}`}>
              <div className={styles.tabItemText}>
                Selesai
              </div>
            </div>
            <div className={styles.tabItem}>
              <div className={styles.tabItemText}>
                Dibatalkan
              </div>
            </div>
          </div>

          <div className={styles.filterContainer}>
            <div className={styles.filterItem}>
              <div className={styles.filterItemIcon}>
                <Image src="/all.png" width="20px" height="20px" />
              </div>
              <div className={styles.filterItemText}>
                Semua
              </div>
            </div>
            <div className={styles.filterItem}>
              <div className={styles.filterItemIcon}>
                <Image src="/moleculechips.png" width="20px" height="20px" />
              </div>
              <div className={styles.filterItemText}>
                Program Keluarga
              </div>
            </div>
            <div className={styles.filterItem}>
              <div className={styles.filterItemIcon}>
                <Image src="/national.png" width="20px" height="20px" />
              </div>
              <div className={styles.filterItemText}>
                Nasional
              </div>
            </div>
          </div>


          <div className={styles.transactionDoneContainer}>
            <div className={styles.transactionDoneItem}>

              <Image src="/boiling.png" width="64px" height="64px" layout="fixed" />
              <div className={styles.transactionDoneItemTextContainer}>
                <div className={styles.transactionDoneItemText}>
                  Senyawa Kapur Sudah Larut di Dalam Darah
                </div>
                <div className={styles.transactionDoneItemLocation}>
                  <div className={styles.transactionDoneItemLocationIcon}>
                    <Image src="/mappinicongray.png" width="12px" height="12px" />
                  </div>
                  <div className={styles.transactionDoneItemLocationText}>
                    Payakumbuh, Sumatera Barat
                  </div>
                  <div className={styles.separatorDot}></div>
                  <div className={styles.transactionDoneItemCategory}>
                    Berbagi
                  </div>

                </div>
                <div className={styles.transactionDoneItemNominal}>
                  Rp 100.000
                </div>
              </div>


            </div>
            <div className={styles.transactionDoneItem}>

              <Image src="/volcano.png" width="64px" height="64px" layout="fixed" />
              <div className={styles.transactionDoneItemTextContainer}>
                <div className={styles.transactionDoneItemText}>
                  #Siaga Bencana - Solidaritas untuk Korban Bencana Alam
                </div>
                <div className={styles.transactionDoneItemLocation}>
                  <div className={styles.transactionDoneItemLocationIcon}>
                    <Image src="/mappinicongray.png" width="12px" height="12px" />
                  </div>
                  <div className={styles.transactionDoneItemLocationText}>
                    Lumajang, Jawa Timur
                  </div>
                  <div className={styles.separatorDot}></div>
                  <div className={styles.transactionDoneItemCategory}>
                    Nasional
                  </div>
                </div>
                <div className={styles.transactionDoneItemNominal}>
                  Rp 98.000
                </div>

              </div>


            </div>

            <div className={styles.transactionDoneItem}>

              <Image src="/mosque.png" width="64px" height="64px" layout="fixed" />
              <div className={styles.transactionDoneItemTextContainer}>
                <div className={styles.transactionDoneItemText}>
                  Khasmir Charity
                </div>
                <div className={styles.transactionDoneItemLocation}>
                  <div className={styles.transactionDoneItemLocationIcon}>
                    <Image src="/mappinicongray.png" width="12px" height="12px" />
                  </div>
                  <div className={styles.transactionDoneItemLocationText}>
                    Gaza, Palestine
                  </div>
                  <div className={styles.separatorDot}></div>
                  <div className={styles.transactionDoneItemCategory}>
                    Internasional
                  </div>
                </div>
                <div className={styles.transactionDoneItemNominal}>
                  Rp 100.000.000
                </div>

              </div>


            </div>

            <div className={styles.transactionDoneItem}>

              <Image src="/charity.png" width="64px" height="64px" layout="fixed" />
              <div className={styles.transactionDoneItemTextContainer}>
                <div className={styles.transactionDoneItemText}>
                  Program Little Project
                </div>
                <div className={styles.transactionDoneItemLocation}>
                  <div className={styles.transactionDoneItemCategory}>
                    Infaq & Sedekah
                  </div>
                </div>
                <div className={styles.transactionDoneItemNominal}>
                  Rp 100.000
                </div>

              </div>


            </div>
          </div>

        </main>

        <footer className={styles.footer}>
          <BottomNavbar />
        </footer>
      </div >
    </div >
  )
}
